# oc create secret generic alertmanager-alertmanager --from-file=alertmanager.yaml
global:
  smtp_smarthost: outbound.cisco.com:25
  smtp_from: alertmanager-no-reply@cisco.com
route:
  receiver: aims_infra_mailer
receivers:
- name: aims_infra_mailer
  email_configs:
  - to: jaganaga@cisco.com
    text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
    send_resolved: true
  - to: kafka-support@cisco.com
    text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
    send_resolved: true
  webhook_config:
  - url: "http://alertmanager-webhook:8080"
