apiVersion: v1
data:
  alertmanager.yaml: IyBvYyBjcmVhdGUgc2VjcmV0IGdlbmVyaWMgYWxlcnRtYW5hZ2VyLW1haW4gLS1mcm9tLWZpbGU9YWxlcnRtYW5hZ2VyLnlhbWwKZ2xvYmFsOgogIHNtdHBfc21hcnRob3N0OiBvdXRib3VuZC5jaXNjby5jb206MjUKICBzbXRwX2Zyb206IG5vcmVwbHlAY2lzY28uY29tCnJvdXRlOgogIHJlY2VpdmVyOiBjaXNjb19lbWFpbApyZWNlaXZlcnM6Ci0gbmFtZTogY2lzY29fZW1haWwKICBlbWFpbF9jb25maWdzOgogIC0gdG86IGphZ2FuYWdhQGNpc2NvLmNvbQogICAgdGV4dDogInt7IHJhbmdlIC5BbGVydHMgfX17eyAuQW5ub3RhdGlvbnMuZGVzY3JpcHRpb24gfX1cbnt7IGVuZCB9fSIKICAgIHNlbmRfcmVzb2x2ZWQ6IHRydWUK
kind: Secret
metadata:
  creationTimestamp: 2019-03-14T07:03:09Z
  name: alertmanager-alertmanager
  namespace: kafka-1
  resourceVersion: "6619"
  selfLink: /api/v1/namespaces/kafka-1/secrets/alertmanager-alertmanager
  uid: 39503012-4627-11e9-ab2e-2a796af867f1
type: Opaque
