# oc create secret generic alertmanager-alertmanager --from-file=alertmanager.yaml
global:
  smtp_smarthost: outbound.cisco.com:25
  smtp_from: noreply@cisco.com
route:
  receiver: cisco_email
receivers:
- name: cisco_email
  email_configs:
  - to: jaganaga@cisco.com
    text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
    send_resolved: true
