apiVersion: v1
items:
- apiVersion: monitoring.coreos.com/v1
  kind: Alertmanager
  metadata:
    name: alertmanager
    namespace: strimzi
  spec:
    baseImage: prom/alertmanager
    imagePullSecrets:
    - name: cisco-secret
    replicas: 3
    serviceAccountName: prometheus
    version: v0.16.2
    externalUrl: https://alertmanager-aims.cisco.com
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: standard
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
