apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: grafana
          containerPort: 3000
          protocol: TCP
        # readinessProbe:
        #   httpGet:
        #     path: /api/health
        #     port: http
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        # volumeMounts:
        # - name: grafana-config
        #   mountPath: /etc/grafana
        #   readOnly: false
        # - name: grafana-data
        #   mountPath: /var/lib/grafana
        # - name: grafana-datasources
        #   mountPath: /etc/grafana/provisioning/datasources
        #   readOnly: false
        # - name: grafana-dashboards
        #   mountPath: /etc/grafana/provisioning/dashboards
      # volumes:
      # - name: grafana-datasources
      #   configMap:
      #     name: grafana-datasource
      # - name: grafana-dashboards
      #   emptyDir: {}
      # - name: grafana-data
      #   emptyDir: {}
      # - name: grafana-config
      #   configMap:
      #     defaultMode: 420
      #     name: grafana-config
      securityContext:
        runAsNonRoot: true
      serviceAccountName: grafana
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  ports:
  - name: grafana
    port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    name: grafana
  type: ClusterIP
# ---
# apiVersion: v1
# kind: Route
# metadata:
#   name: grafana
# spec:
#   port:
#     targetPort: 3000
#   to:
#     kind: Service
#     name: grafana
#     weight: 100
#   wildcardPolicy: None
# ---
# apiVersion: monitoring.coreos.com/v1
# kind: ServiceMonitor
# metadata:
#   name: grafana
# spec:
#   endpoints:
#   - interval: 15s
#     port: http
#   selector:
#     matchLabels:
#       app: grafana
